# -*- coding: utf-8 -*-
"""Problemas_que_utilizan_funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2OgUhJN_Z_KB9zmS_KEUh4BbFMLx5Mr
"""

#Convertidor a centimetros

conversion = int(input("Qué desea convertir a cm?: 1-pies, 2-pulgadas, 3-yardas"))
if conversion not in (1,2,3):
  print("ERROR")
else:
  cantidad = int(input("Ingrese la cantidad a convertir"))

def c_pies(cm):
  return cantidad * 30.48

def c_pulgadas(cm):
  return cantidad * 2.54

def c_yardas(cm):
  return cantidad * 91.44

if conversion == 1:
  print(cantidad, "pies son", c_pies(cantidad), "cm")

elif conversion == 2:
  print(cantidad, "pulgadas son", c_pulgadas(cantidad), "cm")

elif conversion == 3:
  print(cantidad, "yardas son", c_yardas(cantidad), "cm")

#Calcular área y volumen de un cilindro
import math
PI = math.pi

r= float(input("Ingrese el radio del círculo"))
h = float(input("Ingrese la altura del cilindro"))

def area_cilindro(r,h):
 return (2*PI*r*h) + (2*PI*r**2)

def volumen_cilindro(r,h):
  return PI*r**2*h

print(f"El area del cilindro es: {area_cilindro(r,h):.2f}")
print(f"El volumen del cilindro es: {volumen_cilindro(r,h):.2f}")

#Calcular grado

score = float(input("Ingrese el puntaje (entre 0 y 1): "))

def calcula_grado(score):
    if score < 0 or score > 1:
        return "ERROR"
    elif score > 0.9:
        return "A"
    elif score > 0.8:
        return "B"
    elif score > 0.7:
        return "C"
    elif score > 0.6:
        return "D"
    else:
        return "F"

print(f"La nota correspondiente es: {calcula_grado(score)}")

import math
help(math)

