# -*- coding: utf-8 -*-
"""Tarea1. Programas Utilizando funciones predefinidas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108iYrBXikYAjsEP_qWvrFlSb0tGe2-Q0
"""

# Calcular diagonal
import math
print("Calcudora diagnonal rectangulo")

lado_a = float(input("Escriba el lado a del rectangulo"))
lado_b = float(input("Escriba el lado b de la diagonal"))

resultado = math.sqrt(((lado_a)**2)+(lado_b)**2)

print("El resultado es", resultado)

# Calcular litros de pintura
import math
print("Cuantos litros de pintura se necesitan para n metros cuadrados")

area_a_pintar = float(input("Escriba el area que desea pintar en m3"))
metros3_por_litro = float(input("Escriba cuantos m3 se puden pintar por litro de su pintura"))
resultado = math.ceil(area_a_pintar/metros3_por_litro)

print("Resultado:", resultado)

# Calcular distancia entre 2 puntos
import math
print("Calculadora de distancia entre punto A y punto B")
x1 = int(input("X1"))
y1 = int(input("Y2"))
x2 = int(input("X2"))
y2 = int(input("Y2"))

distancia = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

print(f"distancia={distancia:.2f}")

# ejercicio jugadores futbol

nombre_del_equipo = input("Nombre de su equipo")
num_jugadores = int(input("Cuantos jugadores tiene su equipo?"))
mayores= 0
for i in range(num_jugadores):
  edad = int(input(f" Edad del jugador {i+1}: "))
  if edad >= 18:
    mayores +=1

if mayores >= 11:
  sueldo_jugadores = 0
  for s in range(num_jugadores):
    sueldo = int(input(f"Sueldo del jugador {s+1}: "))
    sueldo_jugadores += sueldo

  print(f"Su equipo es {nombre_del_equipo} con {num_jugadores} numero de jugadores, y {mayores} son mayores, en total el sueldo de su equipo es: {sueldo_jugadores}")

else:
  print("Su equipo no es valido ")