# -*- coding: utf-8 -*-
"""Tarea 5_matrices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKp-P-J1QqBewZE8VcUpsoLUoAqCFcPC
"""

# Ejercicio 1: Diagonal principal

def diagonal_principal(matriz):
    vector_diagonal = []
    for x in range(len(matriz)):
        vector_diagonal.append(matriz[x][x])
    return vector_diagonal

def leer(ren, col):
    matriz = []
    for i in range(ren):
        fila = []
        for j in range(col):
            valor = int(input(f'Elemento [{i}][{j}]: '))
            fila.append(valor)
        matriz.append(fila)
    print('Matriz ingresada:')
    for fila in matriz:
        print(fila)
    return matriz

def main():
    ren = int(input('Número de renglones: '))
    col = int(input('Número de columnas: '))
    if ren != col:
        print('Error: la matriz no es cuadrada')
    else:
        matriz = leer(ren, col)
        diag = diagonal_principal(matriz)
        print('Diagonak principal:', diag)

main()

# Ejercicio 2: Centro de matriz

def centrom(matriz):
    matrizs = []
    for i in range(1, len(matriz) - 1):
        vector = []
        for j in range(1, len(matriz[0]) - 1):
            vector.append(matriz[i][j])
        matrizs.append(vector)
    return matrizs

def leer(ren, col):
    matriz = []
    for i in range(ren):
        fila = []
        for j in range(col):
            valor = int(input(f'Elemento [{i}][{j}]: '))
            fila.append(valor)
        matriz.append(fila)
    print('Matriz ingresada:')
    for fila in matriz:
        print(fila)
    return matriz

def main():
    ren = int(input('Número de renglones: '))
    col = int(input('Número de columnas: '))
    matriz = leer(ren, col)
    centro = centrom(matriz)
    print('Centro de la matriz:')
    for fila in centro:
        print(fila)

main()

# Ejercicio 3: Intercambiar renglones

def leer(ren, col):
    matriz = []
    for i in range(ren):
        fila = []
        for j in range(col):
            valor = int(input(f'Elemento [{i}][{j}]: '))
            fila.append(valor)
        matriz.append(fila)
    print('Matriz ingresada:')
    for fila in matriz:
        print(fila)
    return matriz

def cambiareg(matriz):
    r1 = int(input('Número del primer renglón a intercambiar: ')) - 1
    r2 = int(input('Número del segundo renglón a intercambiar: ')) - 1
    for j in range(len(matriz[0])):
        matriz[r1][j], matriz[r2][j] = matriz[r2][j], matriz[r1][j]
    return matriz

def main():
    ren = int(input('Número de renglones: '))
    col = int(input('Número de columnas: '))
    matriz = leer(ren, col)
    matriz = cambiareg(matriz)
    print('Matriz resultante:')
    for fila in matriz:
        print(fila)

main()