# -*- coding: utf-8 -*-
"""Tarea 3 Problemas Repaso

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOtUQ1dfzZoot-1OjiKRUTMDx6HPFV97
"""

# Marcos Daniel Dominguez Contreras
#Sistema de Gestión de Pedidos
pizza = 10
hamburguesa = 8
ensalada = 7

total = 0

while True:
    pedido = input("Elija su combo ingresando solo la letra: a)Pizza b)Hamburguesa c)Ensalada d)Finalizar pedido\n")
    match pedido:
        case "a":
            print("Eligió Pizza con un precio de $10")
            total += pizza
        case "b":
            print("Eligió Hamburguesa con un precio de $8")
            total += hamburguesa
        case "c":
            print("Eligió Ensalada con un precio de $7")
            total += ensalada
        case "d":
            print(f"Su pedido ha finalizado. El total a pagar es: ${total}")
            break
        case _:
            print("Opción inválida, intente nuevamente.")

# sistema de Consumo de Redes Sociles
trpd = [1,4,3,6,3,8,3]

def screentime(lista):
  if len(lista) == 0:
    return 0
  else:
    return sum(lista) / len(lista)

screentime_horas = screentime(trpd)
print(f"Su tiempo promedio diario en redes sociales es de {screentime_horas:.2f} horas.")

horas_a_minutos = lambda h: h * 60
screentime_minutos = horas_a_minutos(screentime_horas)
print(f"Su tiempo promedio diario en redes sociales es de {screentime_minutos:.2f} minutos por día.")